### ISSUE TITLE
Body Measurement : Form Validations

### ISSUE THREAD

**Issue by jenadrianne** [famasboy88/zywie#26]
- [x]  Weight Measurement Add Form 
![23602242_10208059587926524_431407595_n](https://user-images.githubusercontent.com/23441105/32776283-022772c6-c96d-11e7-8099-c651a487c8df.png)

- [x]  Height Measurement Add Form 

![23549850_10208059587366510_1061975625_n](https://user-images.githubusercontent.com/23441105/32776290-091a09f4-c96d-11e7-8121-6776b87824d4.png)

- [x]  BMI Measurement Add Form 
![23601935_10208059587086503_1284745975_n](https://user-images.githubusercontent.com/23441105/32776284-04e78ba4-c96d-11e7-9bac-7e6c06879338.png)

Notes : 
Max input ug number is 5

**Comment by criscarlotan** [comment]
Added Validations:
-if input exceeds maximum input (5), toast will appear to notify user
Added try-catch checking in input conversion to float to properly catch errors:
-if input conversion to float has error, toast will appear to notify user
