### ISSUE TITLE
Body Measurement : Show All Pages --> Newly added Date should be at the top of the list

### ISSUE THREAD

**Issue by jenadrianne** [famasboy88/zywie#30]
![23574370_10208060403106903_1835907793_n](https://user-images.githubusercontent.com/23441105/32784837-e52ccab8-c98a-11e7-8082-498401f7d5fd.png)

----> the data should be sorted from the most recent to oldest 

Apply to the ff Pages
- [x]  Weight Measurement Show All Pages 
- [x]  Height Measurement Show All Pages 
- [x]  BMI Measurement Show All Pages

**Comment by famasboy88** [comment]
Done ... please check pull request
